version: '3.3'
services:
    svetovid:
        environment:
            - EP=svd-test01
            - PSK=test01
            - SERVER_HOST=lwm2m-test.avsystem.io
            - LOG_LEVEL=info
        volumes:
            - '/home/user/docker_config/svd_test-01:/etc/svetovid/dm'
        image: avspresales.jfrog.io/poc-docker/svetovid-commercial:latest
        restart: unless-stopped
        logging:
#            driver: "local"
            options:
                max-size: 100m
